### ISSUE TITLE
Submission for SC consideration: PEP 678 -- Enriching Exceptions with Notes

### ISSUE THREAD

**Issue by Zac-HD** [python/steering-council#105]
Please consider PEP 678, https://www.python.org/dev/peps/pep-0678/

This proposal arose out [discussions about use of `ExceptionGroup`](https://discuss.python.org/t/accepting-pep-654-exception-groups-and-except/10813/12), as a way to attach extra information when exception chaining is undesirable (e.g. because a library does not wish to change the exception type).  The motivation section discusses use by testing libraries such as Hypothesis and Pytest, with concurrency like Trio or with serial retries, and in teaching environments such as friendly-traceback.

**Comment by encukou** [comment]
Thanks! I've added it to the agenda.

**Comment by Zac-HD** [comment]
Hi @encukou - following additional discussion in [the discuss.python.org](https://discuss.python.org/t/pep-678-enriching-exceptions-with-notes/13374/5) thread since I opened this issue, we are planning some minor changes.  (storing a sequence of strings rather than a string-or-None incurs a little extra complexity, but makes translation use-cases much easier to support).

Up to you whether that should affect the agenda.

**Comment by brettcannon** [comment]
@Zac-HD We will leave it on the agenda but skip over it until you're ready again for us to have a look.

**Comment by Zac-HD** [comment]
We've settled on an updated design with `.add_note(note)` and a `__notes__` attribute, and are now once again ready for consideration by the Steering Council.  Thanks for your patience!

**Comment by brettcannon** [comment]
The PEP is back/still in our agenda.

**Comment by brettcannon** [comment]
One thing I noticed about the PEP is it doesn't actually say what `BaseException.add_note()` does. I assume it appends to the tuple, but the PEP actually doesn't say. It also doesn't address whether the tuple is mutated in-place (since you aren't allowing assignment that means Python could cheat and mutate the tuple in-place), or are you constructing a new tuple on every call to `add_note()`?

I would also suggest tweaking the title of the section https://www.python.org/dev/peps/pep-0678/#store-notes-in-exceptiongroups to say "Store notes in ExceptionGroups only". Otherwise if you didn't know that `ExceptionGroup` inherits from `Exception` you might think `ExceptionGroup` wouldn't be getting `__notes__`.

**Comment by Zac-HD** [comment]
Per https://github.com/python/cpython/pull/31317, it appends to an internal list, we create a new tuple each time - mutating in place seems unsafe when the user might have gotten a reference to the tuple already!  I'll update the text to clarify this, and change the title of that section to "Store notes in `ExceptionGroup`s, but not other `Exception`s".

**Comment by brettcannon** [comment]
> mutating in place seems unsafe when the user might have gotten a reference to the tuple already!

I totally agree, hence wanting the clarification. 😁

**Comment by Zac-HD** [comment]
Irit and I talked this over; the PEP is now clear that the tuple is replaced each time a note is added (so you get the same object on every access between updates), and the implementing PR has been updated accordingly.

**Comment by gvanrossum** [comment]
Why would it matter if a tuple of strings is the same object each time? That's a pure value. (Yes, sure, perf, but that's a quality of implementation issue, shouldn't have to be specified in the PEP. This isn't going to hit O(N^2) territory.

**Comment by Zac-HD** [comment]
I don't think it matters or needs to be specified, but since Brett asked above I wrote it in.  Happy to take that back out if SC agrees.

**Comment by brettcannon** [comment]
My concern is someone is going to store that tuple somewhere thinking it isn't going to change at the moment that they saw it, and then whoops, it does, since tuples are generally viewed as immutable.

**Comment by gvanrossum** [comment]
Of course the tuple would be immutable.

**Comment by brettcannon** [comment]
> Of course the tuple would be immutable.

Then I don't understand your concern. The PEP didn't specify what `add_note()` explicitly did, so I suggested it be clarified. I assumed part of the clarification would say that `__note__` always led to a new tuple after `add_note()` was called (whether that's on access of `__note__` because it's a lazy descriptor or by actually storing a tuple internally I don't care). But my key point was nothing was saying what the semantics were in regards to this and we all know what crazy things one can do at the C level, so I figured being explicit instead of implicit was better.

**Comment by iritkatriel** [comment]
This was the actual change in the pep (https://github.com/python/peps/pull/2377/files).  Do you think it’s over specifying how notes is updated?

**Comment by gvanrossum** [comment]
I put my answer in https://github.com/python/peps/pull/2377#issuecomment-1059613950

**Comment by gpshead** [comment]
Ping us when the PEP text is updated to reflect the simpler version per the current discussions. https://discuss.python.org/t/pep-678-enriching-exceptions-with-notes/13374/74?u=gpshead

**Comment by Zac-HD** [comment]
The PEP text has been updated in https://github.com/python/peps/pull/2456.  The key changes are to make `__notes__` a list, and explicitly decline to specify what should happen if users mess with it directly.

**Comment by gpshead** [comment]
Thanks! **Accepted**: https://discuss.python.org/t/pep-678-enriching-exceptions-with-notes/13374/100
