### ISSUE TITLE
Submission for SC consideration: PEP 686 -- Make UTF-8 mode default

### ISSUE THREAD

**Issue by methane** [python/steering-council#118]
Please consider [PEP 686](https://peps.python.org/pep-0686/).

This PEP proposes that making UTF-8 mode default from Python 3.13.
This is backward incompatible change, but backward compatibility option is provided.

Threads:

* https://discuss.python.org/t/14435
* https://discuss.python.org/t/14737

**Comment by encukou** [comment]
Could you also announce it on the python-dev list?

**Comment by methane** [comment]
I did.
https://mail.python.org/archives/list/python-dev@python.org/message/AQ2ZN475KSTPGUURG4Y3ZKBIDSBOBYHY/

**Comment by encukou** [comment]
The changes this PEP lists for 3.11 are actually close to being merged now. The PEP should be updated to list them as background info rather than “specification”, and say they've already been done.
I don't think that'll affect the SC discussion too much. (In the worst case they can be reverted.)

See [Inada-san's mail](https://mail.python.org/archives/list/python-committers@python.org/message/XVJEAF7S2OORL77QMLLQTWKHLRDFA3KH/) for details.

**Comment by Yhg1s** [comment]
The SC accepts the PEP under the condition that the default change be postponed until 3.15: https://discuss.python.org/t/pep-686-make-utf-8-mode-default/14435/43
