### ISSUE TITLE
PEP 696 Type defaults for TypeVarLikes

### ISSUE THREAD

**Issue by Gobot1234** [python/steering-council#177]
Please consider PEP 696
https://peps.python.org/pep-0696/

* [x] The PEP has been discussed in threads listed in its `Post-History` header
* [x] The PEP was announced on [Discuss](https://discuss.python.org/c/peps/19) (link in `Post-History`)
  
* [x] The PEP includes all relevant [Suggested Sections](https://peps.python.org/pep-0012/#suggested-sections)
* [x] The PEP includes endorsements from the projects/groups/people it helps: Danny Yamamoto the author of discord.py was instrumental in helping determine some of the features and testing the PEP in the discord.py code base.
* [x] The PEP has a CODEOWNERS entry
  

SIG-specific:
* [x] *typing-sig* PEPs: link to Guido/Jelle's confirmation that the PEP captures typing-sig discussions/consensus: yes

cc @JelleZijlstra

**Comment by JelleZijlstra** [comment]
I can confirm that the PEP fairly represents the typing-sig discussion. From the discussion thread, the typing-sig community is generally in support of this PEP.

**Comment by Yhg1s** [comment]
After some consideration the SC has decided we want to defer this PEP until at least 3.13. We would like to see how PEP 695 works out in practice before considering more generics-focused, typing-only syntax changes. (We'll keep the PEP in our review queue, you won't have to resubmit.)

**Comment by rchen152** [comment]
Here is the Typing Council's recommendation on this PEP: https://github.com/python/typing-council/issues/12. Reproduced below for convenience:

The Typing Council recommends accepting PEP 696, "Type Defaults for Type Parameters". The Steering Council previously deferred making a decision on this PEP until it had seen the impact of PEP 695, "Type Parameter Syntax". PEP 695 has been well-received by the typing community, and we believe that PEP 696 builds on the new syntax in a natural way.

The proposed feature improves the usability of generic classes by allowing sensible defaults to be specified for omitted type parameters. The PEP demonstrates the usefulness of this feature with two examples of type definitions in the standard library that would benefit from TypeVar defaults. The PEP allows libraries to evolve their typed interfaces better, since in many cases it would mean authors no longer have to trade off between more accurate typing and new errors and verbosity for existing users. The PEP has been extensively discussed and revised in public typing forums over the past two years and has community support. Reference implementations of the needed runtime and type checker changes are included.

**Comment by Yhg1s** [comment]
The Steering Council has decided to follow the Typing Council's recommendation and accepts PEP 696.
