### ISSUE TITLE
SC Ruling on appropriate uses for commit messages

### ISSUE THREAD

**Issue by ethanfurman** [python/steering-council#31]
Please make a statement about commit messages and their content, so we all know what to expect.

This is in reference to the recent commit message detailing the PEP-8 removal of Strunk & White as a guide for writing comments because it supported White Supremacy and encouraged "whiteness".

If such messages are acceptable then a requirement to have supporting links embedded so others can verify the accuracy of such statements would, hopefully, go a long way in averting more threads like those that resulted in this instance.

**Comment by aeros** [comment]
I'd like to clarify that I'm specifically +1 on having an official stance on this issue from the SC (regarding the commit message contents) and for revising the commit message if it is not deemed to be appropriate going forward.

However, I'm indifferent about the link embedding. For me, it's more about whether we want to politicize commit messages or use them as _any kind of platform_. My personal stance on that matter is that commit messages should only be a technical summary of what the changes involved. In the case of the PEP 8 change, I would consider a commit message along these lines to be more appropriate:

```
Remove Strunk & White reference from PEP 8
* Clarify intent of using "clear and easily understandable" English
```

(Note that it does not contain any opinionated additional content, and only serves as a description of the changes made.)

**Comment by warsaw** [comment]
Speaking as a core developer, not for the SC, I am fine with the actual change to PEP 8, but I agree that the political content in the commit message was inappropriate and unnecessary to describe the technical change.  However, I think it's too late to change the original commit message.

**Comment by brettcannon** [comment]
We can still, as an SC, come up with some basic guidelines of what we expect out of a commit message. (IOW we are not ignoring this request, we are just swamped with other, time-sensitive things.)

**Comment by aeros** [comment]
> We can still, as an SC, come up with some basic guidelines of what we expect out of a commit message.

Thanks for the update, @brettcannon. There's currently some guidelines for writing commit messages in the [devguide](https://devguide.python.org/pullrequest/#making-good-commits); that might be a good place to elaborate upon the existing ones after the SC makes an announcement about this particular scenario, for future reference.

**Comment by RMJ10** [comment]
Any projected timescales on this?  I honestly don't feel like this is being taken seriously at the moment. which is not exactly causing me to feel less offended.

**Comment by pitrou** [comment]
Personally, I would be a bit patient about this. It's not easy when you're a volunteer (and perhaps less when you're a bunch of volunteers with diverse opinions) to carve quality time for controversial topics.

**Comment by brettcannon** [comment]
@RMJ10 what @pitrou said. This whole event happened at a bad time for coordination on the SC due to vacations, work commitments, etc. Dealing with the whole event is also bigger than you may realize, plus there are other unrelated things occurring that we are having to coordinate and deal with on top of this one topic.

Or to put it another way, I have been dealing with this topic on a daily basis since the incident occurred (which includes weekends and while I was camping and not supposed to be doing anything Python-related or even tech-related so I could just relax; obviously didn't happen), so the fact that it isn't fully resolved should act as a hint as how much work has and will continue to be dedicated to this until it's fully resolved.

**Comment by RMJ10** [comment]
A week and a half isn't exactly rushing.  @brettcannon while I'm perfectly happy to take you at your word for how much you have been working on this, it's completely invisible from outside.  All I get to see is the SC attempting to stifle discussion with a heavy hand (and seriously, the close message on python/peps#1526 is practically begging to be taken badly.  I'm choosing not to, but I'm only about 70% sure I'm right).

I've done my time volunteering in much more overtly political situations (I not-so-jokingly referred to it as the full time job on top of my full time job), and the one thing that became abundantly clear to me is that you don't let things like this fester.  Time is not your friend here.  As I said on the mailing list, "If the answer [...] is a prevarication, non-answer or silence, people will still draw their own conclusions.  I mention this merely to reinforce the idea that these things are still answers as well as hostages to fortune."

**Comment by brettcannon** [comment]
@RMJ10 It may be invisible but I am also not up to blog or somehow publicly document that I'm dealing with this or what's going on (I have already had to step away from social media for the month to manage my stress level due to all of this).

And it isn't that I disagree that addressing things sooner would be better, it also isn't like we planned for it to take this long either. Everyone is a volunteer and we simply can only move so fast when you have work, personal lives, time zones, vacations, and a pandemic to contend with. So perhaps in hindsight we could have said, "we are looking into it" explicitly, but I honestly would have assumed most people knew we were dealing with it and not exactly ignoring the problem either. Plus this is the first "crisis" we are having to deal with that's like this so there will be some learning afterwards.

Anyway, hopefully this is enough for you to understand that things are being dealt with as fast as we can manage it and we ask that everyone to please be patient.

**Comment by ethanfurman** [comment]
Thank you, Brett, and everyone else working on this.  On top of all the other time-sinks we also just passed the postponed US tax deadline of July 15.

If any of you have to put this issue aside for a couple weeks, do so.  I'd rather have you all around for the long haul than have this issue resolved a few days earlier.

**Comment by aeros** [comment]
@ethanfurman 
> If any of you have to put this issue aside for a couple weeks, do so. I'd rather have you all around for the long haul than have this issue resolved a few days earlier.

I couldn't agree more. Regardless of how important a topic may seem in the moment, we have to all remember that contributing to Python is supposed to be an enjoyable activity, completely independent of whether the contributor is new, core, or a member of the Steering Council. Although some may have more responsibilities, it's not worthwhile to burn yourself out over them. 

Please take care of yourselves, and prioritize that over getting us a response to this issue slightly sooner. I can't speak for everyone of course, but I'm perfectly willing to wait as long as necessary if the SC needs some additional breathing room.

**Comment by brettcannon** [comment]
The SC met today and have decided we are not going to be editing the commit message, although some on the SC suggested they probably would have tried wordsmithing it a bit before merging the PR. But in general we are happy with the current guidance in the devguide.

If people want to make specific suggestions for  changes to the devguide they can and we would be happy to consider it, but the general guidance there seems adequate and we don't want to get too prescriptive with this due to a reaction of a single commit message.
