### ISSUE TITLE
Meetings/updates?

### ISSUE THREAD

**Issue by brainwane** [python/steering-council#37]
Hi! I just noticed that there haven't been any updates in this repository for several months; is there someplace else I should be looking for meeting outcomes and updates? Thank you!

**Comment by matham** [comment]
I was kinda wandering this myself because I have been trying to follow any decisions or updates for PEP 622, and I think there has been some feedback about it to the PEP authors from what I could tell elsewhere, but there has been no updates here.

Perhaps I'm mistaken and only final PEP decisions are posted to this repo and not everything (of importance) discussed by the steering council?

**Comment by brettcannon** [comment]
@brainwane it's simply us forgetting. @ejodlowska has been busy and no one else on the council has thought about putting out revised notes on meeting (since we have to scrub them for public consumption).

@matham trawling through meeting notes won't be the best way to get updates. If you truly want to know what's going on with that PEP I would ask the PEP authors. But what I can tell you is they were given feedback and they are working on a rewrite ATM, so I would wait for that to get published first.
