### ISSUE TITLE
A reminder to please submit discussion topics to Python Language Summit  

### ISSUE THREAD

**Issue by Mariatta** [python/steering-council#57]
From the SC's [February update](https://github.com/python/steering-council/blob/main/updates/2021-02-steering-council-update.md), it seems like there is intent from the SC to submit a topic about the TOML module.

Since we still have not received any proposal yet from steering council members, thought I'd be proactive and remind you all to submit the topic before March 22 (7 days from today).

Info: https://us.pycon.org/2021/summits/language/

I'm also interested to hear about with the issue with Python and Debian distro issues. Would this be something that you all want to discuss at the summit as well? Do you want to invite folks from Debian to join?

**Comment by brettcannon** [comment]
No intent from me to submit a talk on a TOML module, but I submitted a more broad one on the stdlib already (and since the TOML idea is mostly from me that probably means no TOML talk 😉 ).

And we cannot discuss the Debian situation as it has not been resolved yet.

I'll leave this open for any other SC members to see.

**Comment by Mariatta** [comment]
The sign up period has closed. Thanks.
