### ISSUE TITLE
Submission for SC consideration: PEP 649 -- Deferred Evaluation Of Annotations Using Descriptors

### ISSUE THREAD

**Issue by larryhastings** [python/steering-council#63]
I apologize for the lateness of the submission--but here it is, PEP 649.

I'll keep an eye on this issue in case I can answer any questions for the committee here.

Thank you for your time.

**Comment by pablogsal** [comment]
Thanks, @larryhastings! I will add it to our agenda, although there's a bit of a backlog at the moment we will try to get it as soon as possible :)

**Comment by warsaw** [comment]
Latest communication from the SC: https://mail.python.org/archives/list/python-dev@python.org/thread/VIZEBX5EYMSYIJNDBF6DMUMZOCWHARSO/

**Comment by gpshead** [comment]
We're tentatively accepting the PEP by telling the next SC to do so in three months in absence of new compelling reasons not to. See https://discuss.python.org/t/pep-649-deferred-evaluation-of-annotations-tentatively-accepted/21331 for what that means and as a place for further discussion.

**Comment by larryhastings** [comment]
I've updated PEP 649.

**Comment by Yhg1s** [comment]
After some consideration we've decided to accept the PEP _for 3.13_, rather than 3.12, due to the size and intricacy of the implementation. We do want to get this into 3.13 _early_, though, so if this could land shortly after the 3.12 beta 1 cut that would be great. For now we're assuming it won't need a future import in 3.13.
