### ISSUE TITLE
PEP 394: Change review request

### ISSUE THREAD

**Issue by encukou** [python/steering-council#8]
I submitted a PR that substantially modifies PEP 394: https://github.com/python/peps/pull/989

I'm not sure about procedures for modification of existing PEPs. It would make sense that they need to be approved by the SC or BDFL-Delegate.
Is that the case? If so, I'd like to ask for a pronouncement/delegate.

**Comment by gvanrossum** [comment]
In this case I definitely think the SC should be involved. When I was BDFL I recall at least once stopping a similar change to this same PEP. I'm feeling more mellow about it (things in the distro world are changing) but if the BDFL could stop it previously, the SC should have a say now.

**Comment by ncoghlan** [comment]
The three main ways I see of resolving this:

- we just iterate directly on the PR until it achieves SC consensus to publish the revised guidance
- the SC appoints @warsaw as our delegate and we merge the change once Barry is happy with it
- we appoint Matthias Klose as the delegate (since he's the Debian Python maintainer)

(The first option is my preference, but I'm mentioning the other two since they both seem viable to me)

My rationale for that, is that the current PR mostly reflects an attempt to bring Fedora and Red Hat's existing plans into alignment with the upstream guidance, as the distro level state of affairs has changed a lot since the PEP was first written, and the problem we're now dealing with is "How to remove Python 2?" rather than "How to introduce Python 3?".

Since we don't actually have the power to *dictate* what distributions do, it makes sense to offer them guidance that they already want to follow, and if the Fedora/RHEL and Debian/Ubuntu maintainers can agree on particular guidance making sense, it's quite likely good advice for distributions in general :)

**Comment by vstinner** [comment]
@gvanrossum @ncoghlan: Is there any update on this issue?

**Comment by vstinner** [comment]
> @gvanrossum @ncoghlan: Is there any update on this issue?

Oh, a discussion is on-going at: https://github.com/python/peps/pull/989

**Comment by hugovk** [comment]
This issue may be closed now https://github.com/python/peps/pull/989 is merged.

**Comment by ncoghlan** [comment]
Thanks for the reminder, @hugovk!

For the record, the review process we adopted was a hybrid of options 1 & 2 in my list above - while all SC members were invited to review the PR if they wanted to do so, we also made @warsaw's approval a blocking criterion for actually merging the change.
